### ISSUE TITLE
Slow Miner not working

### ISSUE THREAD

**Issue by jason7861** [CPScript/Crypto-Tools#2]
\BTC-Tools\Bitcoin\2>python miner.py
address:bc1q4904y3a4c78f4x40l3tvdk0nkjwpwvyda9lyud nonce:38c967d9
host:solo.ckpool.org port:3333
[{'id': None,
  'method': 'mining.notify',
  'params': ['6485163800006fef',
             '4c465e0cde5627984ccb640f1ada2dba0a1fe7cc0001bd900000000000000000',
             '01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff35032e220c0004449191640481ec7a080c',
             '0a636b706f6f6c112f736f6c6f2e636b706f6f6c2e6f72672fffffffff031617d82500000000160014a95f5247b5c78e9a9aaffc56c6d9f3b49c17308d54b7c5000000000016001451ed61d2f6aa260cc72cdf743e4e436a82c010270000000000000000266a24aa21a9ed040528da68ea377d299f091c5f11c8d3f0a2638bd3716b50145ea84c4034d67e00000000',
             ['8a1142dd722d22e5fc12cb8439897a1de6331a66b272629b836fc6f301bb9cab',
              '2a68936584cfc84e58526713ec00c9b38b48c80e763e1ced3cbb15d44e7a958c',
              '21baf07c66ae3776a018256bc976c4bfdb0399c8ee4f099af28df49a85c686a0',
              '50b1805c5858416ee523fb2332f4d443c9c360b80053c0bfc6803300a52f30f4',
              '478b76984928ce80c2b137b862d72fae382e944eac6e38da3ca85cb1d04903e8',
              '2a45f78f6827e93770a687d91cac038d5195a07f367319f1cd8abc5055e1b15b',
              'cad7433be2277acd3181a1be33ffc2d5fb699e7543deee48d56f6444bbaa4b85',
              'c1f3756d795d4ccb9369fa00cde7ff18aa7d62f6e32833d0411517e6e2161223',
              '5881c7d27b52be5ce6b01098b1b2be6e30ea2db4685c29ea8955ee779fcac15c',
              'e3321d80159bec72fe75b485403cbe6a6488b0305d5b00f0f1dcd263570ff192',
              '0777e6b2bfb7f6247cc7b8f0f0ee5a7ab0fa1de6e68e4f1fbf6391c67ebb5f36',
              '342a66754e52c43ab1e0a8c7d281d20b5535450e1f919820bf7c470e07cf49d7'],
             '20000000',
             '1705606d',
             '64919144',
             True]}]
nbits:1705606d target:00000000000000000005606d0000000000000000000000000000000000000000

coinbase:
01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff35032e220c0004449191640481ec7a080c960dd16400000000000000000a636b706f6f6c112f736f6c6f2e636b706f6f6c2e6f72672fffffffff031617d82500000000160014a95f5247b5c78e9a9aaffc56c6d9f3b49c17308d54b7c5000000000016001451ed61d2f6aa260cc72cdf743e4e436a82c010270000000000000000266a24aa21a9ed040528da68ea377d299f091c5f11c8d3f0a2638bd3716b50145ea84c4034d67e00000000

coinbase hash:b'30ce3deedbde516d2ad4b940c61b38346d476d7c15b9756cc4e819b96d19450a'

merkle_root:a808429af7e222d72c2e8c5684e6de2ed56c1039c50d71a0046165bc7bab68c7

blockheader:
200000004c465e0cde5627984ccb640f1ada2dba0a1fe7cc0001bd900000000000000000a808429af7e222d72c2e8c5684e6de2ed56c1039c50d71a0046165bc7bab68c71705606d6491914438c967d9000000800000000000000000000000000000000000000000000000000000000000000000000000000000000080020000

hash: 59a817fb47d88625fbc9f76230d9e1f49a06cb1bf2ff1dfbb51dab7da8a2e396
failed mine, hash is greater than target

**Comment by 0u44** [comment]
wallet doesn't exist... try to change it and tell me if that works

**Comment by 0u44** [comment]
also, the slower your computer is... the slower ittle mine... for quicker mining you would need more VRam & Ram
